# Generated by Django 3.0.8 on 2021-08-09 10:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispdlts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispdlts_name', models.CharField(max_length=200)),
                ('dispdlts_address1', models.TextField(blank=True, max_length=300, null=True)),
                ('dispdlts_address2', models.TextField(blank=True, max_length=300, null=True)),
                ('dispdlts_loc', models.CharField(blank=True, max_length=15, null=True)),
                ('dispdlts_pin', models.CharField(blank=True, max_length=15, null=True)),
                ('dispdlts_stcd', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.TextField(blank=True, max_length=20, null=True)),
                ('plan_value', models.IntegerField(blank=True, null=True)),
                ('monthly_invoice_limit', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_title', models.CharField(blank=True, max_length=100, null=True)),
                ('business_address', models.TextField(blank=True, max_length=400, null=True)),
                ('business_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('business_gst', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipdlts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipdlts_gstin', models.CharField(max_length=20)),
                ('shipdlts_lglnm', models.CharField(max_length=20)),
                ('shipdlts_trdnm', models.CharField(max_length=20)),
                ('shipdlts_addr1', models.TextField(blank=True, max_length=300, null=True)),
                ('shipdlts_addr2', models.TextField(blank=True, max_length=300, null=True)),
                ('shipdlts_loc', models.CharField(max_length=20)),
                ('shipdlts_pin', models.CharField(max_length=20)),
                ('shipdlts_stcd', models.CharField(max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('product_unit', models.CharField(max_length=50)),
                ('product_gst_percentage', models.FloatField()),
                ('product_rate_with_gst', models.FloatField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_slno', models.CharField(max_length=30)),
                ('item_prdesc', models.CharField(max_length=30)),
                ('item_isservc', models.CharField(max_length=30)),
                ('item_hsncd', models.CharField(max_length=30)),
                ('item_freeqty', models.CharField(max_length=30)),
                ('item_qty', models.CharField(max_length=30)),
                ('item_barcde', models.CharField(max_length=30)),
                ('item_unit', models.CharField(max_length=30)),
                ('item_unitprice', models.CharField(max_length=30)),
                ('item_totamt', models.CharField(max_length=30)),
                ('item_discount', models.CharField(max_length=30)),
                ('item_pretaxval', models.CharField(max_length=30)),
                ('item_assamt', models.CharField(max_length=30)),
                ('item_gstrt', models.CharField(max_length=30)),
                ('item_igstamt', models.CharField(max_length=30)),
                ('item_cgstamt', models.CharField(max_length=30)),
                ('item_sgstamt', models.CharField(max_length=30)),
                ('item_cesrt', models.CharField(max_length=30)),
                ('item_cesamt', models.CharField(max_length=30)),
                ('item_cesnonadvlamt', models.CharField(max_length=30)),
                ('item_statecesrt', models.CharField(max_length=30)),
                ('item_statecesamt', models.CharField(max_length=30)),
                ('item_statecesnonadvlamt', models.CharField(max_length=30)),
                ('item_othchrg', models.CharField(max_length=30)),
                ('item_totitemval', models.CharField(max_length=30)),
                ('item_ordlineref', models.CharField(max_length=30)),
                ('item_orgcntry', models.CharField(max_length=30)),
                ('item_prdslno', models.CharField(max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('invoice_json', models.TextField()),
                ('inventory_reflected', models.BooleanField(default=True)),
                ('invoice_dispdlts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Dispdlts')),
                ('invoice_shipdlts', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Shipdlts')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('change', models.IntegerField(default=0)),
                ('change_type', models.IntegerField(choices=[(0, 'Other'), (1, 'Purchase'), (2, 'Production'), (3, 'Item'), (4, 'Sales')], default=0)),
                ('description', models.TextField(blank=True, max_length=600, null=True)),
                ('associated_invoice', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Invoice')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Item')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0)),
                ('alert_level', models.IntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Item')),
                ('last_log', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.InventoryLog')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('plan_end_date', models.DateField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='GstInvoicing.Plan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
