# Generated by Django 3.0.8 on 2021-08-15 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GstInvoicing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorylog',
            name='associated_invoice',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_dispdlts',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_shipdlts',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='monthly_invoice_limit',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryLog',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
