# Generated by Django 3.0.8 on 2021-08-15 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GstInvoicing', '0002_auto_20210815_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_prdesc',
            new_name='item_prddesc',
        ),
    ]
